#!/usr/bin/env node

/**
 * Smriti V1 API Tester
 *
 * Dependency-free integration tester for the current Smriti API surface.
 *
 * Requirements:
 *   - Node.js 18+ (uses built-in fetch)
 *   - Node/Express backend running on port 5000
 *   - FastAPI assessment engine running on port 8000 (optional for internal tests)
 *
 * Run:
 *   node api_tester.js
 *
 * Optional environment variables:
 *   BACKEND_URL=http://127.0.0.1:5000
 *   ASSESSMENT_URL=http://127.0.0.1:8000
 *   TEST_PATIENT_EMAIL=patient@example.com
 *   TEST_CAREGIVER_EMAIL=caregiver@example.com
 *
 * The test data is based on the current verified Smriti V1 API contract.
 */

'use strict';

const BACKEND_URL = process.env.BACKEND_URL || 'http://127.0.0.1:5000';
const ASSESSMENT_URL =
  process.env.ASSESSMENT_URL || 'http://127.0.0.1:8000';

const PATIENT_EMAIL =
  process.env.TEST_PATIENT_EMAIL || 'patient@example.com';
const CAREGIVER_EMAIL =
  process.env.TEST_CAREGIVER_EMAIL || 'caregiver@example.com';

const results = {
  passed: 0,
  failed: 0,
  skipped: 0,
};

// Every HTTP interaction is documented here and written to disk at the end.
// JWTs are redacted so this file is safe to commit as development evidence.
const apiLog = {
  metadata: {
    generated_at: new Date().toISOString(),
    backend_url: BACKEND_URL,
    assessment_url: ASSESSMENT_URL,
    description:
      'Smriti V1 API request/response evidence generated by api_tester.js',
  },
  interactions: [],
};

function redactSecrets(value) {
  if (typeof value === 'string') {
    // Redact JWT-like bearer tokens and common JWT response values.
    if (
      value.length > 40 &&
      value.split('.').length === 3 &&
      /^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(value)
    ) {
      return '[REDACTED_JWT]';
    }
    return value;
  }

  if (Array.isArray(value)) {
    return value.map(redactSecrets);
  }

  if (value && typeof value === 'object') {
    const output = {};
    for (const [key, item] of Object.entries(value)) {
      if (
        ['authorization', 'access_token', 'token', 'password'].includes(
          key.toLowerCase()
        )
      ) {
        output[key] = '[REDACTED]';
      } else {
        output[key] = redactSecrets(item);
      }
    }
    return output;
  }

  return value;
}

function sanitizeHeaders(headers) {
  const output = {};
  if (!headers) return output;

  for (const [key, value] of Object.entries(headers)) {
    output[key] =
      key.toLowerCase() === 'authorization'
        ? 'Bearer [REDACTED_JWT]'
        : value;
  }

  return output;
}

function logInteraction({
  request,
  response,
  name,
  purpose,
  expected,
  observed,
}) {
  apiLog.interactions.push({
    id: apiLog.interactions.length + 1,
    name,
    purpose,
    expected: expected || null,
    request: redactSecrets(request),
    response: {
      status: response.status,
      headers: sanitizeHeaders(response.headers),
      body: redactSecrets(response.body),
    },
    observed: observed || null,
  });
}

async function writeApiLog() {
  const outputPath =
    process.env.API_LOG_FILE ||
    'api_test_requests_responses.json';

  await require('fs').promises.writeFile(
    outputPath,
    JSON.stringify(apiLog, null, 2),
    'utf8'
  );

  console.log(`\nAPI evidence log written to: ${outputPath}`);
  console.log(
    `Documented HTTP interactions: ${apiLog.interactions.length}`
  );
}

function pass(name, details = '') {
  results.passed += 1;
  console.log(`✅ PASS  ${name}${details ? ` — ${details}` : ''}`);
}

function fail(name, details = '') {
  results.failed += 1;
  console.error(`❌ FAIL  ${name}${details ? ` — ${details}` : ''}`);
}

function skip(name, details = '') {
  results.skipped += 1;
  console.log(`⚠️  SKIP  ${name}${details ? ` — ${details}` : ''}`);
}

function assert(condition, name, details = '') {
  if (condition) {
    pass(name, details);
    return true;
  }

  fail(name, details);
  return false;
}

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

async function request(baseUrl, path, options = {}) {
  const url = `${baseUrl}${path}`;

  let response;
  try {
    response = await fetch(url, options);
  } catch (error) {
    const failedResponse = {
      url,
      status: 0,
      headers: new Headers(),
      body: null,
      raw: '',
    };

    logInteraction({
      name: `${options.method || 'GET'} ${path}`,
      purpose: 'HTTP request',
      request: {
        method: options.method || 'GET',
        url,
        headers: options.headers || {},
        body: options.body ? safeJsonParse(options.body) : null,
      },
      response: failedResponse,
      observed: { network_error: error.message },
    });

    throw new Error(`Request failed for ${url}: ${error.message}`);
  }

  const text = await response.text();

  let body = null;
  if (text.length > 0) {
    try {
      body = JSON.parse(text);
    } catch {
      body = text;
    }
  }

  const result = {
    url,
    status: response.status,
    headers: response.headers,
    body,
    raw: text,
  };

  logInteraction({
    name: `${options.method || 'GET'} ${path}`,
    purpose: 'HTTP request',
    request: {
      method: options.method || 'GET',
      url,
      headers: options.headers || {},
      body: options.body ? safeJsonParse(options.body) : null,
    },
    response: result,
  });

  return result;
}

function safeJsonParse(value) {
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}

function bearer(token) {
  return {
    Authorization: `Bearer ${token}`,
  };
}

function assertJson(response, name) {
  return assert(
    isPlainObject(response.body) || Array.isArray(response.body),
    name,
    `HTTP ${response.status}`
  );
}

function logResponse(label, response) {
  console.log(`\n--- ${label} ---`);
  console.log(`HTTP ${response.status}`);
  console.log(
    typeof response.body === 'string'
      ? response.body
      : JSON.stringify(response.body, null, 2)
  );
}

async function login(email) {
  const response = await request(BACKEND_URL, '/auth/login', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ email }),
  });

  assert(response.status === 200, `POST /auth/login (${email})`);

  if (response.status !== 200 || !isPlainObject(response.body)) {
    return null;
  }

  const token = response.body.access_token;
  assert(
    typeof token === 'string' && token.length > 0,
    `Login returns access_token (${email})`
  );

  return {
    token,
    user: response.body.user,
  };
}

function buildMemoryMatchTelemetry(sessionId, patientId) {
  return {
    session_id: sessionId,
    patient_id: patientId,
    activity_id: 'memory_match_v1',
    num_pairs: 4,
    started_at: '2026-09-07T19:00:00Z',
    ended_at: '2026-09-07T19:01:24Z',
    events: [
      {
        event: 'card_selected',
        timestamp: 1725735605123,
        card_id: 'card_7',
        position: 7,
      },
      {
        event: 'card_selected',
        timestamp: 1725735606710,
        card_id: 'card_2',
        position: 2,
      },
      {
        event: 'match_result',
        timestamp: 1725735606725,
        card_1: 'card_7',
        card_2: 'card_2',
        is_match: false,
      },
      {
        event: 'card_selected',
        timestamp: 1725735612010,
        card_id: 'card_7',
        position: 7,
      },
      {
        event: 'card_selected',
        timestamp: 1725735613400,
        card_id: 'card_5',
        position: 5,
      },
      {
        event: 'match_result',
        timestamp: 1725735613415,
        card_1: 'card_7',
        card_2: 'card_5',
        is_match: true,
      },
    ],
  };
}

async function testFastApiOptional() {
  console.log('\n==============================');
  console.log('FASTAPI INTERNAL SERVICE TESTS');
  console.log('==============================');

  try {
    const health = await request(ASSESSMENT_URL, '/');
    assert(
      health.status === 200,
      'FastAPI GET / health',
      `expected 200, got ${health.status}`
    );
    assert(
      isPlainObject(health.body) && health.body.status === 'ok',
      'FastAPI health response shape'
    );

    const payload = {
      profile: {
        patient_id: 'P_API_TEST',
        current_difficulty: 1,
      },
      raw_session: buildMemoryMatchTelemetry(
        'sess_api_test',
        'P_API_TEST'
      ),
    };

    const processed = await request(
      ASSESSMENT_URL,
      '/v1/process-session',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      }
    );

    assert(
      processed.status === 200,
      'FastAPI POST /v1/process-session',
      `expected 200, got ${processed.status}`
    );

    if (processed.status === 200 && isPlainObject(processed.body)) {
      const body = processed.body;

      assert(body.session_id === 'sess_api_test', 'Assessment session_id');
      assert(body.domain === 'MEMORY', 'Assessment domain');
      assert(isPlainObject(body.features), 'Assessment features object');
      assert(
        body.features.pairs_presented === 4,
        'Assessment pairs_presented',
        'expected authoritative num_pairs=4'
      );
      assert(
        body.features.pairs_recalled === 1,
        'Assessment pairs_recalled'
      );
      assert(
        body.features.repeated_selections === 1,
        'Assessment repeated_selections'
      );
      assert(
        isPlainObject(body.normalized_features),
        'Assessment normalized_features object'
      );
      assert(
        isPlainObject(body.domain_score),
        'Assessment domain_score object'
      );
      assert(
        typeof body.domain_score.score === 'number' &&
          body.domain_score.score >= 0 &&
          body.domain_score.score <= 1,
        'Assessment domain score is within [0,1]'
      );
      assert(
        body.baseline === null,
        'First HTTP session baseline is null'
      );
      assert(
        body.deviation === null,
        'First HTTP session deviation is null'
      );
      assert(
        isPlainObject(body.longitudinal) &&
          body.longitudinal.trend === 'INSUFFICIENT_DATA',
        'First HTTP session longitudinal state'
      );
    }

    return true;
  } catch (error) {
    skip(
      'FastAPI internal service tests',
      error.message
    );
    return false;
  }
}

/**
 * Output file format:
 *
 * {
 *   metadata: {
 *     generated_at,
 *     backend_url,
 *     assessment_url,
 *     description,
 *     results
 *   },
 *   interactions: [
 *     {
 *       id,
 *       name,
 *       purpose,
 *       expected,
 *       request: { method, url, headers, body },
 *       response: { status, headers, body },
 *       observed
 *     }
 *   ]
 * }
 *
 * This deliberately captures request/response JSON rather than only PASS/FAIL,
 * making the file useful as API evidence and frontend integration reference.
 */
async function testBackend() {
  console.log('\n==============================');
  console.log('NODE / EXPRESS API TESTS');
  console.log('==============================');

  // Health/root route
  try {
    const root = await request(BACKEND_URL, '/');

    // The public backend may or may not expose GET /.
    if (root.status === 200) {
      pass('Backend GET /', 'HTTP 200');
    } else if (root.status === 404) {
      skip('Backend GET /', 'route not implemented');
    } else {
      fail('Backend GET /', `HTTP ${root.status}`);
    }
  } catch (error) {
    fail('Backend connectivity', error.message);
    return;
  }

  const patient = await login(PATIENT_EMAIL);
  const caregiver = await login(CAREGIVER_EMAIL);

  if (!patient || !caregiver) {
    fail('Authentication setup', 'could not obtain both test tokens');
    return;
  }

  const patientToken = patient.token;
  const caregiverToken = caregiver.token;
  const patientId = patient.user?.id || 'P001';

  // Patient profile
  let response = await request(BACKEND_URL, '/patients/me', {
    headers: bearer(patientToken),
  });
  assert(response.status === 200, 'GET /patients/me');
  if (response.status === 200) {
    assertJson(response, 'GET /patients/me returns JSON');
    assert(
      isPlainObject(response.body) &&
        response.body.id === patientId,
      'Patient profile has expected patient id'
    );
  }

  // Progress
  response = await request(BACKEND_URL, '/patients/me/progress', {
    headers: bearer(patientToken),
  });
  assert(response.status === 200, 'GET /patients/me/progress');
  if (response.status === 200) {
    assertJson(response, 'GET /patients/me/progress returns JSON');
  }

  // Reminders
  response = await request(BACKEND_URL, '/patients/me/reminders', {
    headers: bearer(patientToken),
  });
  assert(response.status === 200, 'GET /patients/me/reminders');
  if (response.status === 200) {
    assert(
      Array.isArray(response.body),
      'GET /patients/me/reminders returns array'
    );
  }

  // Medications
  response = await request(BACKEND_URL, '/patients/me/medications', {
    headers: bearer(patientToken),
  });
  assert(response.status === 200, 'GET /patients/me/medications');
  if (response.status === 200) {
    assert(
      Array.isArray(response.body),
      'GET /patients/me/medications returns array'
    );
  }

  // Activities
  response = await request(BACKEND_URL, '/activities', {
    headers: bearer(patientToken),
  });
  assert(response.status === 200, 'GET /activities');
  if (response.status === 200) {
    assert(
      Array.isArray(response.body) && response.body.length > 0,
      'GET /activities returns non-empty array'
    );
  }

  // Activity detail
  response = await request(BACKEND_URL, '/activities/A101', {
    headers: bearer(patientToken),
  });
  assert(response.status === 200, 'GET /activities/A101');
  if (response.status === 200) {
    assert(
      isPlainObject(response.body) &&
        typeof response.body.title === 'string',
      'GET /activities/A101 response shape'
    );
  }

  // Existing session history before test completion
  response = await request(
    BACKEND_URL,
    '/patients/me/session-history',
    {
      headers: bearer(patientToken),
    }
  );
  assert(
    response.status === 200,
    'GET /patients/me/session-history (before)'
  );
  const historyBefore =
    response.status === 200 && Array.isArray(response.body)
      ? response.body
      : [];

  // Start session
  response = await request(
    BACKEND_URL,
    '/activities/memory_match_v1/sessions',
    {
      method: 'POST',
      headers: bearer(patientToken),
    }
  );
  assert(
    response.status === 201,
    'POST /activities/memory_match_v1/sessions'
  );

  if (
    response.status !== 201 ||
    !isPlainObject(response.body) ||
    typeof response.body.session_id !== 'string'
  ) {
    fail(
      'Session start response contains session_id',
      'cannot continue session completion test'
    );
  } else {
    const sessionId = response.body.session_id;

    assert(
      response.body.status === 'STARTED',
      'Session start status is STARTED'
    );

    // Complete session
    const telemetry = buildMemoryMatchTelemetry(
      sessionId,
      patientId
    );

    response = await request(
      BACKEND_URL,
      `/activities/memory_match_v1/sessions/${encodeURIComponent(
        sessionId
      )}/complete`,
      {
        method: 'POST',
        headers: {
          ...bearer(patientToken),
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ telemetry }),
      }
    );

    assert(
      response.status === 200,
      'POST /activities/:id/sessions/:session_id/complete'
    );

    if (response.status === 200 && isPlainObject(response.body)) {
      const body = response.body;

      assert(
        body.session_id === sessionId,
        'Completed assessment session_id matches started session'
      );
      assert(
        body.status === 'COMPLETED',
        'Completed session status is COMPLETED'
      );
      assert(
        body.domain === 'MEMORY',
        'Completed session domain is MEMORY'
      );
      assert(
        isPlainObject(body.features),
        'Completed session contains features'
      );
      assert(
        body.features.pairs_presented === 4,
        'Completed session pairs_presented === 4'
      );
      assert(
        isPlainObject(body.normalized_features),
        'Completed session contains normalized_features'
      );
      assert(
        isPlainObject(body.domain_score),
        'Completed session contains domain_score'
      );
      assert(
        typeof body.domain_score.score === 'number' &&
          body.domain_score.score >= 0 &&
          body.domain_score.score <= 1,
        'Completed domain score is within [0,1]'
      );
      assert(
        Object.prototype.hasOwnProperty.call(body, 'baseline'),
        'Completed result includes baseline field'
      );
      assert(
        Object.prototype.hasOwnProperty.call(body, 'deviation'),
        'Completed result includes deviation field'
      );
      assert(
        isPlainObject(body.longitudinal),
        'Completed result includes longitudinal field'
      );

      // Fetch history again and verify the new result was persisted.
      response = await request(
        BACKEND_URL,
        '/patients/me/session-history',
        {
          headers: bearer(patientToken),
        }
      );

      assert(
        response.status === 200,
        'GET /patients/me/session-history (after)'
      );

      if (response.status === 200 && Array.isArray(response.body)) {
        assert(
          response.body.length >= historyBefore.length,
          'Session history does not shrink after completion'
        );

        const found = response.body.some(
          (item) => item?.session_id === sessionId
        );

        assert(
          found,
          'Completed session appears in patient session history'
        );
      }
    }
  }

  // Caregiver list
  response = await request(
    BACKEND_URL,
    '/caregiver/patients',
    {
      headers: bearer(caregiverToken),
    }
  );
  assert(response.status === 200, 'GET /caregiver/patients');
  if (response.status === 200) {
    assert(
      Array.isArray(response.body),
      'GET /caregiver/patients returns array'
    );
  }

  // Caregiver alerts
  response = await request(
    BACKEND_URL,
    '/caregiver/alerts',
    {
      headers: bearer(caregiverToken),
    }
  );
  assert(response.status === 200, 'GET /caregiver/alerts');
  if (response.status === 200) {
    assert(
      Array.isArray(response.body),
      'GET /caregiver/alerts returns array'
    );
  }

  // Caregiver patient history
  response = await request(
    BACKEND_URL,
    `/caregiver/patients/${encodeURIComponent(
      patientId
    )}/session-history`,
    {
      headers: bearer(caregiverToken),
    }
  );
  assert(
    response.status === 200,
    'GET /caregiver/patients/:id/session-history'
  );
  if (response.status === 200) {
    assert(
      Array.isArray(response.body),
      'Caregiver session history returns array'
    );
  }

  // Auth failure
  response = await request(BACKEND_URL, '/patients/me');
  assert(
    response.status === 401,
    'GET /patients/me without token returns 401'
  );

  // Role failure
  response = await request(
    BACKEND_URL,
    '/caregiver/alerts',
    {
      headers: bearer(patientToken),
    }
  );
  assert(
    response.status === 403,
    'Patient accessing caregiver route returns 403'
  );
}

async function main() {
  console.log('==============================================');
  console.log('       SMRITI V1 API INTEGRATION TESTER       ');
  console.log('==============================================');
  console.log(`Backend URL:    ${BACKEND_URL}`);
  console.log(`Assessment URL: ${ASSESSMENT_URL}`);
  console.log(`API log file:   ${process.env.API_LOG_FILE || 'api_test_requests_responses.json'}`);
  console.log('');

  try {
    await testBackend();
    await testFastApiOptional();
  } catch (error) {
    console.error('\nFATAL TEST ERROR');
    console.error(error);
    results.failed += 1;
  } finally {
    apiLog.metadata.results = {
      passed: results.passed,
      failed: results.failed,
      skipped: results.skipped,
      result: results.failed > 0 ? 'FAIL' : 'PASS',
    };

    try {
      await writeApiLog();
    } catch (logError) {
      console.error(
        `\nWARNING: could not write API evidence log: ${logError.message}`
      );
      results.failed += 1;
    }
  }

  console.log('\n==============================');
  console.log('FINAL RESULTS');
  console.log('==============================');
  console.log(`Passed:  ${results.passed}`);
  console.log(`Failed:  ${results.failed}`);
  console.log(`Skipped: ${results.skipped}`);

  if (results.failed > 0) {
    console.error('\nAPI TEST RESULT: FAIL');
    process.exitCode = 1;
  } else {
    console.log('\nAPI TEST RESULT: PASS');
  }
}

main();
